### ISSUE TITLE
ar-run hangs 

### ISSUE THREAD

**Issue by levinas** [kbase/assembly#167]
I had a strange case where the run command hangs on upload for a dataset that is not too big. 

```
on sal:
$ cd /space2/fangfang/ar-tests/Francisella_tularensis_Schu_S4/FSC043
ar-run -m FSC043.5K -a spades ?only_assembler=False --pair SRR1061345_1.fastq SRR1061345_2.fastq 
```

With the `--curl` option, it worked:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4428M  100   536  100 4428M      7  58.8M  0:01:16  0:01:15  0:00:01 57.5M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4428M  100   536  100 4428M      6  56.3M  0:01:29  0:01:18  0:00:11 55.4M
```

Will look into this tomorrow.

**Comment by sebhtml** [comment]
This is reproducible.

This hangs:

seb@kbase-devel:~/bug-167$ time arast run -m FSC043.5K -a spades ?only_assembler=False --pair SRR1061345_1.fastq SRR1061345_2.fastq

This works fine:

$ time arast run --curl -m FSC043.5K -a spades ?only_assembler=False --pair SRR1061345_1.fastq SRR1061345_2.fastq 

2m46.466s

**Comment by sebhtml** [comment]
Timeline:

1. arast client requests object storage information:

140.221.67.189 - - [12/Feb/2015:17:00:18] "GET /shock HTTP/1.1" 200 42 "" "python-requests/2.5.1 CPython/2.7.3 Linux/3.2.0-76-virtual"

2.  the arast client establish a TCP connection with the object storage service (Shock):

root@kbase-devel:/kbase/arast# ps aux|grep arast.py|grep -v grep
seb      22236  9.2 20.1 4593344 4549892 pts/6 S+   17:00   0:15 python /home/seb/production-assembly/assembly/deployment/pybin/arast.py run -m FSC043.5K -a spades ?only_assembler=False --pair SRR1061345_1.fastq SRR1061345_2.fastq
root@kbase-devel:/kbase/arast# lsof|grep 140.221.67.235
python    22236        seb    5u     IPv4             117429        0t0        TCP kbase-devel.novalocal:53932->140.221.67.235:7445 (ESTABLISHED)

**Comment by sebhtml** [comment]
Got it:

[seb@sal bug-167]# ls -lL|grep fastq
-rw-rw-r-- 1 fangfang fangfang 4643268046 Jul 14  2014 SRR1061345_1.fastq
-rw-rw-r-- 1 fangfang fangfang 4643268046 Jul 14  2014 SRR1061345_2.fastq

It seems that the ssl Python library does not like big files...

  File "/usr/lib/python2.7/ssl.py", line 298, in send
    v = self._sslobj.write(data)
OverflowError: string longer than 2147483647 bytes

[seb@sal bug-167]# ./command.sh 
Traceback (most recent call last):
  File "/kb/deployment/pybin/arast.py", line 410, in <module>
    main()
  File "/kb/deployment/pybin/arast.py", line 388, in main
    run_command()
  File "/kb/deployment/pybin/arast.py", line 375, in run_command
    cmd_run(args, aclient, usage, clientlog)
  File "/kb/deployment/pybin/arast.py", line 167, in cmd_run
    data = prepare_assembly_data(args, aclient, usage)
  File "/kb/deployment/pybin/arast.py", line 318, in prepare_assembly_data
    f_info = aclient.upload_data_file_info(word, curl=curl)
  File "/kb/deployment/lib/assembly/client.py", line 53, in upload_data_file_info
    res = self.shock.upload_reads(filename, curl=curl)
  File "/kb/deployment/lib/assembly/shock.py", line 124, in upload_reads
    return self.upload_file(filename, filetype='reads', curl=curl, auth=auth)
  File "/kb/deployment/lib/assembly/shock.py", line 111, in upload_file
    res = self._post_file(filename, filetype, auth)
  File "/kb/deployment/lib/assembly/shock.py", line 200, in _post_file
    r = requests.post(self.posturl, files=files, headers=self.headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 327, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 493, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 291, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 805, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/ssl.py", line 329, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.7/ssl.py", line 298, in send
    v = self._sslobj.write(data)
OverflowError: string longer than 2147483647 bytes

**Comment by levinas** [comment]
Great. Does that mean we can't rely on requests after all?

**Comment by sebhtml** [comment]
First step is to add a timeout.

**Comment by sebhtml** [comment]
I get the overflow with the arast client on sal.mcs.anl.gov. So technically, it does not hang.

On seb-kbase-devel.mcs.anl.gov, it just hangs.

**Comment by cbun** [comment]
Would there be any reason not to just default to curl?

**Comment by sebhtml** [comment]
I think we should use pycurl.

**Comment by sebhtml** [comment]
reproducer:

seb@kbase-devel:~/bug-167$ ls -l SRR1061345_1.fastq
-rw-rw-r-- 1 seb seb 4643268046 Feb 12 16:35 SRR1061345_1.fastq
seb@kbase-devel:~/bug-167$ arast upload --single SRR1061345_1.fastq

**Comment by sebhtml** [comment]
requests.post loads everything in memory when doing a multipart-encoded operation. 

This loads all the files in memory:

sendfiles = {'file1': open('file1.txt', 'rb'), 'file2': open('file2.txt', 'rb')}
r = requests.post('http://httpbin.org/post', files=sendfiles)

This streams the file:

r = requests.post('http://httpbin.org/post', data=open('file1.txt', 'rb')

* https://github.com/kennethreitz/requests/issues/295
* http://stackoverflow.com/questions/15973204/using-python-requests-to-bridge-a-file-without-loading-into-memory
* http://stackoverflow.com/questions/22915295/python-requests-post-and-big-content
* http://stackoverflow.com/questions/22918916/python-post-multiple-multipart-encoded-files

**Comment by levinas** [comment]
@cbun requests can hold an in-memory attribute file when posting to shock. That was considered desirable. If the streaming mode works, we can keep it.

**Comment by sebhtml** [comment]
possible solutions

https://pypi.python.org/pypi/requests-toolbelt/0.3.1
https://pypi.python.org/pypi/poster/

**Comment by sebhtml** [comment]
To reproduce the leak:

arast upload  --single SRR1061345_1.fastq

**Comment by sebhtml** [comment]
I have a fix that solves the memory usage. I don't know if it will solve the strange problem on SAL with ssl, but it is not hanging in my devel environment with the fix.

**Comment by sebhtml** [comment]
I am doing a final test to make sure it is sane. Then I will push.
