### ISSUE TITLE
ar-stat -n option not documented

### ISSUE THREAD

**Issue by brettin** [kbase/assembly#278]
[brettin@maple biosamples]$ ar-stat -h

Usage: ar-stat [-h] [-w] [-j JOB | -l | --data-json DATA] [-n STAT_N] [-s server_addr]

Query status of running jobs

Optional arguments:
  -h, --help            show this help message and exit
  -j JOB, --job JOB     get status of a specific job ID
  -l, --list-data       list data objects
  --data-json DATA      print the information of a data ID
  -s server_addr        specify ARAST server address
  -w, --watch           monitor in realtime (only works in Linux and Mac shell)
  --version             print ARAST client version number

**Comment by levinas** [comment]
Tom,

Please source this latest arast env on maple:

$ source ~fangfang/P3-arast/user-env.sh

I’ll ask Bob to update the deployment in /vol/kbase..

**Comment by levinas** [comment]
Bob just deployed the new release on maple.

**Comment by brettin** [comment]
thanks!
