### ISSUE TITLE
velvet in auto recipe does not recognize FASTA files

### ISSUE THREAD

**Issue by levinas** [kbase/assembly#301]
This bug can be reproduced against the dev server.

```
$ ar-run -s 140.221.67.201 --pair forward.fa reverse.fa
```
On the server, SPAdes launched the assembly correctly:
Command: spades.py --pe2-1 forward.fa --pe2-2 reverse.fa -t 4 ...

But velvet missed all the read files and tried to run:
```
Command: velveth velvet_e28ac24f-d408-4f7f-9925-f6c62280ebd3 29
```

However, if I launch with the `-a velvet` option explicitly, the job runs. Is there an issue with the wasp interpretation?

**Comment by levinas** [comment]
This bug affects single end libraries too.

**Comment by levinas** [comment]
This is probably due to bayers hammer not working for fasta files which have no quality scores. As a result, nothing gets to run. We should modify the bhammer plugin to handle fasta files gracefully. 

Two options: 
1. Detect FASTA files and bypass the error correction
2. Assign the original reads to `processed_reads` if error correction fails. 

@cbun do we already have a FASTA detector in the plugin?

**Comment by cbun** [comment]
Are you sure Spades runs this correctly?

BayesHammer will run, which also uses `spades.py` but theoretically all the assemblers should fail.

**Comment by levinas** [comment]
Yes, all assemblers failed. This fixes it.
